### ISSUE TITLE
HMDA-Regulator No Longer Generating LAR Data

### ISSUE THREAD

**Issue by PatrickHSI** [cfpb/hmda-platform#2557]
There has been a persistent issue since February 13th 2019 in which HMDA-Regulator fails to generate  LAR regulator data during the nightly builds. 

@zencircle  has identified the process that generates the HMDA-Regulator data is killed soon after it starts due to resource issues. 

Possible Scala bug as to why we're not seeing any errors :

https://github.com/scala/bug/issues/9554

**Comment by PatrickHSI** [comment]
It appears the production deployment consumes the following error. Hinting  that the query loading all of the table data into memory is causing the memory issue. 

Looking into an alternative method to stream the data from postgres.

```
hmda-regulator [ERROR] [02/19/2019 02:41:44.151] [larTask-scheduler-1] [akka.actor.ActorSystemImpl(larTask)] exception on LARS’ timer thread
hmda-regulator java.lang.OutOfMemoryError: GC overhead limit exceeded
hmda-regulator 	at akka.dispatch.AbstractNodeQueue.<init>(AbstractNodeQueue.java:32)
hmda-regulator 	at akka.actor.LightArrayRevolverScheduler$TaskQueue.<init>(LightArrayRevolverScheduler.scala:304)
hmda-regulator 	at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:269)
hmda-regulator 	at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:235)
hmda-regulator 	at java.lang.Thread.run(Thread.java:748)
