### ISSUE TITLE
hmda-platform fails with --dev option

### ISSUE THREAD

**Issue by zencircle** [cfpb/hmda-platform#2841]
Command
`docker run -ti --rm -p 8080:8080 -p 8081:8081 hmda/hmda-platform:latest`

See errors below 
```
Starting Cassandra on port 9042
06/17 14:26:25 ERROR[main] o.a.c.s.StartupChecks - cassandra.jmx.local.port missing from cassandra-env.sh, unable to start local JMX service.
..
[2019-06-17 14:26:33,620][INFO ][pool-8-thread-1] DataStax Java driver 3.6.0 for Apache Cassandra
[2019-06-17 14:26:33,627][INFO ][pool-8-thread-1] Detected Guava >= 19 in the classpath, using modern compatibility layer
Exception in thread "main" java.lang.IllegalArgumentException: Cannot build a cluster without contact points
	at com.datastax.driver.core.Cluster.checkNotEmpty(Cluster.java:169)
	at com.datastax.driver.core.Cluster.<init>(Cluster.java:162)
``

**Comment by zencircle** [comment]
Duplicate  https://github.com/cfpb/hmda-platform/issues/2841
