### ISSUE TITLE
Parser errors when non text data is inserted

### ISSUE THREAD

**Issue by omnipresent07** [cfpb/hmda-platform#3373]
It appears if XLSM data is inserted, the parser API's error out and throw below stack traces:

```
Caused by: com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:111)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.skipField(CodedInputStream.java:662)
	at hmda.persistence.serialization.submission.processing.commands.FieldParserErrorMessage.mergeFrom(FieldParserErrorMessage.scala:67)
	at hmda.persistence.serialization.submission.processing.commands.FieldParserErrorMessage.mergeFrom(FieldParserErrorMessage.scala:9)
	at scalapb.LiteParser$.readMessage(LiteParser.scala:18)
	at hmda.persistence.serialization.submission.processing.events.HmdaRowParsedErrorMessage.mergeFrom(HmdaRowParsedErrorMessage.scala:80)
	at hmda.persistence.serialization.submission.processing.events.HmdaRowParsedErrorMessage.mergeFrom(HmdaRowParsedErrorMessage.scala:9)
	at scalapb.LiteParser$.parseFrom(LiteParser.scala:12)
	at scalapb.GeneratedMessageCompanion.parseFrom(GeneratedMessageCompanion.scala:195)
	at scalapb.GeneratedMessageCompanion.parseFrom$(GeneratedMessageCompanion.scala:195)
```

We need to test a case by uploading non text data and ensure API doesn't throw stacktrace while calling parser api endpoint.

**Comment by omnipresent07** [comment]
This is happening because of a separate reason. The data that is being fetched from `HmdaParserError` Entitity was inserted on October 9th. However, on October 17th a non backwards compatible change was introduced to this protobuf in order to better help the users with parser error messaging. Now when this data is being fetched, we get a protobuf error.
