### ISSUE TITLE
v2.20.4 on docker hub doesn't run

### ISSUE THREAD

**Issue by jmurphy-asurity** [cfpb/hmda-platform#4095]
Thank you for pushing your images to docker hub, but I can't get it to work.  I modified your docker-compose.yml to pull ` image: hmda/hmda-platform:v2.20.4`, and ran `docker-compose up hmda-platform`.  Here is the pertinent portion of the logs:
```hmda-platform_1     | [2021-04-29 13:25:06,669][INFO ][main] Kafka version: 2.4.1
hmda-platform_1     | [2021-04-29 13:25:06,669][INFO ][main] Kafka commitId: c57222ae8cd7866b
hmda-platform_1     | [2021-04-29 13:25:06,669][INFO ][main] Kafka startTimeMs: 1619702706669
hmda-platform_1     | [2021-04-29 13:25:06,701][INFO ][hmda2-akka.actor.default-dispatcher-10] Actor started at akka://hmda2/user/HmdaPersistence
hmda-platform_1     | [2021-04-29 13:25:06,704][INFO ][hmda2-akka.actor.default-dispatcher-4] Actor started at akka://hmda2/user/HmdaValidation
hmda-platform_1     | [2021-04-29 13:25:06,717][INFO ][hmda2-akka.actor.default-dispatcher-11] Actor started at akka://hmda2/user/HmdaPublication
hmda-platform_1     | Uncaught error from thread [hmda2-akka.actor.default-dispatcher-14]: 'akka.http.scaladsl.server.Directive ch.megard.akka.http.cors.scaladsl.CorsDirectives$.cors()', shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[hmda2]
hmda-platform_1     | java.lang.NoSuchMethodError: 'akka.http.scaladsl.server.Directive ch.megard.akka.http.cors.scaladsl.CorsDirectives$.cors()'
hmda-platform_1     |   at hmda.api.ws.routes.BaseWsApi$.route(BaseWsApi.scala:17)
hmda-platform_1     |   at hmda.api.ws.HmdaWSApi$.$anonfun$apply$1(HmdaWSApi.scala:34)
hmda-platform_1     |   at akka.actor.typed.internal.BehaviorImpl$DeferredBehavior$$anon$1.apply(BehaviorImpl.scala:119)
hmda-platform_1     |   at akka.actor.typed.Behavior$.start(Behavior.scala:168)
hmda-platform_1     |   at akka.actor.typed.internal.adapter.ActorAdapter.preStart(ActorAdapter.scala:281)
hmda-platform_1     |   at akka.actor.Actor.aroundPreStart(Actor.scala:548)
hmda-platform_1     |   at akka.actor.Actor.aroundPreStart$(Actor.scala:548)
hmda-platform_1     |   at akka.actor.typed.internal.adapter.ActorAdapter.aroundPreStart(ActorAdapter.scala:256)
hmda-platform_1     |   at akka.actor.ActorCell.create(ActorCell.scala:641)
hmda-platform_1     |   at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
hmda-platform_1     |   at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
hmda-platform_1     |   at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
hmda-platform_1     |   at akka.dispatch.Mailbox.run(Mailbox.scala:230)
hmda-platform_1     |   at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
hmda-platform_1     |   at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
hmda-platform_1     |   at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1176)
hmda-platform_1     |   at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1647)
hmda-platform_1     |   at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1614)
hmda-platform_1     |   at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
hmda-platform_1     | [2021-04-29 13:25:06,949][ERROR][hmda2-akka.actor.default-dispatcher-4] Uncaught error from thread [hmda2-akka.actor.default-dispatcher-14]: 'akka.http.scaladsl.server.Directive ch.megard.akka.http.cors.scaladsl.CorsDirectives$.cors()', shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[hmda2]
hmda-platform_1     | java.lang.NoSuchMethodError: 'akka.http.scaladsl.server.Directive ch.megard.akka.http.cors.scaladsl.CorsDirectives$.cors()'
hmda-platform_1     |   at hmda.api.ws.routes.BaseWsApi$.route(BaseWsApi.scala:17)
hmda-platform_1     |   at hmda.api.ws.HmdaWSApi$.$anonfun$apply$1(HmdaWSApi.scala:34)
hmda-platform_1     |   at akka.actor.typed.internal.BehaviorImpl$DeferredBehavior$$anon$1.apply(BehaviorImpl.scala:119)
hmda-platform_1     |   at akka.actor.typed.Behavior$.start(Behavior.scala:168)
hmda-platform_1     |   at akka.actor.typed.internal.adapter.ActorAdapter.preStart(ActorAdapter.scala:281)
hmda-platform_1     |   at akka.actor.Actor.aroundPreStart(Actor.scala:548)
hmda-platform_1     |   at akka.actor.Actor.aroundPreStart$(Actor.scala:548)
hmda-platform_1     |   at akka.actor.typed.internal.adapter.ActorAdapter.aroundPreStart(ActorAdapter.scala:256)
hmda-platform_1     |   at akka.actor.ActorCell.create(ActorCell.scala:641)
hmda-platform_1     |   at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
hmda-platform_1     |   at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
hmda-platform_1     |   at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:295)
hmda-platform_1     |   at akka.dispatch.Mailbox.run(Mailbox.scala:230)
hmda-platform_1     |   at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
hmda-platform_1     |   at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
hmda-platform_1     |   at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1176)
hmda-platform_1     |   at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1647)
hmda-platform_1     |   at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1614)
hmda-platform_1     |   at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)```

**Comment by omnipresent07** [comment]
Thank you, we have updated the image. Everything should be working now.
