### ISSUE TITLE
HmdaFileUploadSpec fails without a `clean` before `test`

### ISSUE THREAD

**Issue by hkeeler** [cfpb/hmda-platform#423]
The following error occurs when running `sbt test` without first doing an `sbt clean`.  @nickgrippin mentioned that the Akka Persistence data isn't being cleared out post-test.  This is likely the culprit.

```
[info] HmdaFileUploadSpec:
[info] A HMDA File
[info] - must be persisted *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: expected HmdaFileUploadState(Map(1466450321914 -> 4)), found HmdaFileUploadState(Map(1466450112373 -> 4, 1466450321914 -> 4))
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:350)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:326)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:734)
[info]   at hmda.api.processing.HmdaFileUploadSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(HmdaFileUploadSpec.scala:26)
[info]   at hmda.api.processing.HmdaFileUploadSpec$$anonfun$1$$anonfun$apply$mcV$sp$2.apply(HmdaFileUploadSpec.scala:21)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   ...
[info] - must recover with event *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: expected HmdaFileUploadState(Map(1466450321914 -> 4)), found HmdaFileUploadState(Map(1466450112373 -> 4))
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:350)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:326)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:734)
[info]   at hmda.api.processing.HmdaFileUploadSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(HmdaFileUploadSpec.scala:35)
[info]   at hmda.api.processing.HmdaFileUploadSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(HmdaFileUploadSpec.scala:29)
[info]   at hmda.api.processing.HmdaFileUploadSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(HmdaFileUploadSpec.scala:29)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
[info] - must recover with from snapshot *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: expected HmdaFileUploadState(Map(1466450321914 -> 4)), found HmdaFileUploadState(Map(1466450112373 -> 4))
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:350)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:326)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:734)
[info]   at hmda.api.processing.HmdaFileUploadSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(HmdaFileUploadSpec.scala:49)
[info]   at hmda.api.processing.HmdaFileUploadSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(HmdaFileUploadSpec.scala:39)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   ...
```

**Comment by nickgrippin** [comment]
Closed in #425
