### ISSUE TITLE
Leap year exception in data publisher

### ISSUE THREAD

**Issue by rkovalik-raft** [cfpb/hmda-platform#4746]
The unit tests for 2021 quarters in [QuarterTimeBarrierTest](https://github.com/cfpb/hmda-platform/blob/db9bffb202eadf44fa4181bedf3650e60ab74ee5/hmda-data-publisher/src/test/scala/hmda/publisher/helper/QuarterTimeBarrierTest.scala#L17) are failing and need to be fixed.

**Comment by rkovalik-raft** [comment]
This is failing for the year 2023 as well. From prod logs:
```
[2024-01-19 03:30:00,001][ERROR][hmda-data-publisher-akka.actor.default-dispatcher-202] Invalid date 'DayOfYear 366' as '2023' is not a leap year
java.time.DateTimeException: Invalid date 'DayOfYear 366' as '2023' is not a leap year
	at java.base/java.time.LocalDate.ofYearDay(LocalDate.java:296)
	at hmda.publisher.helper.QuarterTimeBarrier$.getEndDateForQuarter(QuarterTimeBarrier.scala:93)
	at hmda.publisher.helper.QuarterTimeBarrier.runIfStillRelevant(QuarterTimeBarrier.scala:34)
	at hmda.publisher.scheduler.LarScheduler$$anonfun$receive$1.$anonfun$applyOrElse$5(LarScheduler.scala:147)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at hmda.publisher.scheduler.LarScheduler$$anonfun$receive$1.applyOrElse(LarScheduler.scala:144)
```
