### ISSUE TITLE
Two sporadically failing tests

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform#547]
Juan wrote: 

> Build failure in master for hmda-platform. HmdaFileParser is logging at debug level, but one of the tests from the last merged PR is using an InfoFilter to check for messages, I think the issue is [here](https://github.com/cfpb/hmda-platform/blob/master/persistence/src/test/scala/hmda/persistence/processing/HmdaFileParserSpec.scala#L83). Can someone produce a hotfix for this? 

test output:

```
[info] - must process parse completed message from event stream *** FAILED ***
[info]   java.lang.AssertionError: received 1 excess messages on DebugFilter(Some(akka://test-system/user/$a),Left(Parsing completed for 12345-2017-1),true)
[info]   at akka.testkit.EventFilter.intercept(TestEventListener.scala:116)
[info]   at hmda.api.processing.LocalHmdaEventProcessorSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply$mcV$sp(LocalHmdaEventProcessorSpec.scala:51)
[info]   at hmda.api.processing.LocalHmdaEventProcessorSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(LocalHmdaEventProcessorSpec.scala:49)
[info]   ...
```

**Comment by jmarin** [comment]
Actually, the test failure that Travis is reporting is different, it's on `HmdaFileParserSpec` see https://travis-ci.org/cfpb/hmda-platform/builds/156598159

**Comment by schbetsy** [comment]
Hmm. Here's the failure on master (that Juan linked to):
```
[info] - must read entire raw file *** FAILED ***
[info]   java.lang.AssertionError: timeout (3 seconds) waiting for 1 messages on InfoFilter(Some(akka://test-system/user/$f),Left(Parsing completed for 12345-2017-2),true)
[info]   at akka.testkit.EventFilter.intercept(TestEventListener.scala:114)
[info]   at hmda.persistence.processing.HmdaFileParserSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(HmdaFileParserSpec.scala:83)
[info]   at hmda.persistence.processing.HmdaFileParserSpec$$anonfun$1$$anonfun$apply$mcV$sp$5.apply(HmdaFileParserSpec.scala:73)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   ...
```
However, I haven't been able to replicate that failure locally. I've gotten the failure in the top comment (2 of the 6 times I've run tests locally), but I haven't gotten the one on Travis.

I'll keep looking into it.

**Comment by schbetsy** [comment]
I re-ran the Travis build where `HmdaFileParserSpec` had a failure, and this time the tests all passed. So the build is no longer broken, but these sporadic failures have caused plenty of confusion and delay. I'm leaving this issue open until they are fixed.

**Comment by lgdean** [comment]
See also [this comment](https://github.com/cfpb/hmda-platform/issues/524#issuecomment-240898291) and others on #524

**Comment by lgdean** [comment]
You mentioned it in the meeting today, and then I happened to see a failure later in the day (at the head of `master`). Including all the debug messages, some of which are surely irrelevant, just in case it helps:

```
[info] LocalHmdaEventProcessorSpec:
[info] Event processor
[info] - must process upload start message from event stream *** FAILED ***
[info]   Created was not equal to Uploading (LocalHmdaEventProcessorSpec.scala:119)
[info] - must process upload completed message from event stream
[info] - must process parse started message from event stream
[info] - must process parse completed message from event stream
[info] - must process 'parsingCompletedWithErrors' message from event stream
[info] - must process validation started message from event stream
[info] - must process validation completed with errors from event stream
[info] - must process validation completed from event stream
[DEBUG] [09/30/2016 15:28:37.283] [test-system-akka.actor.default-dispatcher-3] [akka://test-system/user/supervisor/submissions-testUploadComp-2017] Actor stopped at akka://test-system/user/supervisor/submissions-testUploadComp-2017
[DEBUG] [09/30/2016 15:28:37.283] [test-system-akka.actor.default-dispatcher-14] [akka://test-system/user/supervisor/submissions-testParseComp-2017] Actor stopped at akka://test-system/user/supervisor/submissions-testParseComp-2017
[DEBUG] [09/30/2016 15:28:37.284] [test-system-akka.actor.default-dispatcher-16] [akka://test-system/user/supervisor/HmdaFileValidator-testUploadComp-2017-1] Actor stopped at akka://test-system/user/supervisor/HmdaFileValidator-testUploadComp-2017-1
[DEBUG] [09/30/2016 15:28:37.284] [test-system-akka.actor.default-dispatcher-17] [akka://test-system/user/supervisor/submissions-testEvents1-2017] Actor stopped at akka://test-system/user/supervisor/submissions-testEvents1-2017
[DEBUG] [09/30/2016 15:28:37.284] [test-system-akka.actor.default-dispatcher-13] [akka://test-system/user/supervisor/HmdaFileValidator-testParseComp-2017-1] Actor stopped at akka://test-system/user/supervisor/HmdaFileValidator-testParseComp-2017-1
[DEBUG] [09/30/2016 15:28:37.284] [test-system-akka.actor.default-dispatcher-5] [akka://test-system/user/supervisor/HmdaFileParser-testUploadComp-2017-1] Actor stopped at akka://test-system/user/supervisor/HmdaFileParser-testUploadComp-2017-1
[DEBUG] [09/30/2016 15:28:37.284] [test-system-akka.actor.default-dispatcher-23] [akka://test-system/user/supervisor] Actor stopped at akka://test-system/user/supervisor
[DEBUG] [09/30/2016 15:28:37.285] [test-system-akka.actor.default-dispatcher-23] [EventStream] shutting down: StandardOutLogger started
[DEBUG] [09/30/2016 15:28:37.295] [pool-4-thread-2] [EventStream(akka://test-system)] logger log1-TestEventListener started
[DEBUG] [09/30/2016 15:28:37.295] [pool-4-thread-2] [EventStream(akka://test-system)] Default Loggers started
[DEBUG] [09/30/2016 15:28:37.299] [test-system-akka.actor.default-dispatcher-7] [akka.persistence.Persistence(akka://test-system)] Create plugin: inmemory-journal akka.persistence.inmemory.journal.InMemoryAsyncWriteJournal
[DEBUG] [09/30/2016 15:28:37.300] [test-system-akka.actor.default-dispatcher-7] [akka.persistence.Persistence(akka://test-system)] Create plugin: inmemory-snapshot-store akka.persistence.inmemory.snapshot.InMemorySnapshotStore
```

**Comment by schbetsy** [comment]
We're no longer seeing these particular failures. Closing this issue. 

When we see other intermittent failures, we can create new issues for them.
