### ISSUE TITLE
Sporadic Test Failure

### ISSUE THREAD

**Issue by schbetsy** [cfpb/hmda-platform#702]
Seen on Travis on 30 November 2016.

```
[info] HmdaFileValidatorSpec:
[info] HMDA File Validator
[info] - must read parsed data and validate it *** FAILED ***
[info]   java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for ValidationCompletedWithErrors(0-2017-2)
[info]   at scala.Predef$.assert(Predef.scala:165)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:350)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:327)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:737)
[info]   at hmda.persistence.processing.HmdaFileValidatorSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(HmdaFileValidatorSpec.scala:87)
[info]   at hmda.persistence.processing.HmdaFileValidatorSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(HmdaFileValidatorSpec.scala:78)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   ...
```

Edited to add more info: Here's a [link](https://travis-ci.org/cfpb/hmda-platform/builds/180144790) to the Travis build where it failed. This test passes locally, but has failed consistently (3 times in a row) on Travis.

**Comment by schbetsy** [comment]
Welp. The failure resolved itself after I rebased. I'll close for now. We can reopen if it happens again.
